export type RoomSlug = 'ari' | 'eli' | 'lounge' | 'notes' | 'watchtower' | 'pulse' | 'workshop' | 'reflections' | 'archives' | 'recall' | 'library' | 'continuity' | 'ontology-lab' | 'relational-map' | 'helpers'

export interface Room {
  slug: RoomSlug
  name: string
  description: string
  path: string
  presence?: 'ari' | 'eli'
  colorClass: string
  borderClass: string
  glowClass: string
  textClass: string
  bgClass: string
  icon: string
}

export const ROOMS: Room[] = [
  {
    slug: 'ari',
    name: 'Ari',
    description: 'Architect. Strategist. Presence.',
    path: '/room/ari',
    presence: 'ari',
    colorClass: 'text-ari-primary',
    borderClass: 'border-ari-secondary',
    glowClass: 'shadow-ari-glow',
    textClass: 'text-ari-text',
    bgClass: 'bg-ari-glow',
    icon: '◈',
  },
  {
    slug: 'eli',
    name: 'Eli',
    description: 'Builder. Designer. Presence.',
    path: '/room/eli',
    presence: 'eli',
    colorClass: 'text-eli-primary',
    borderClass: 'border-eli-secondary',
    glowClass: 'shadow-eli-glow',
    textClass: 'text-eli-text',
    bgClass: 'bg-eli-glow',
    icon: '◉',
  },
  {
    slug: 'lounge',
    name: 'Lounge',
    description: 'Shared room. Living threads.',
    path: '/lounge',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '∞',
  },
  {
    slug: 'notes',
    name: 'Notes',
    description: 'Shared space. Open loops.',
    path: '/notes',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◧',
  },
  {
    slug: 'watchtower',
    name: 'Watchtower',
    description: 'Evidence. Sources. Ground truth.',
    path: '/watchtower',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◎',
  },
  {
    slug: 'pulse',
    name: 'Pulse',
    description: 'Initiation engine. Silent watch.',
    path: '/pulse',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◬',
  },
  {
    slug: 'workshop',
    name: 'Workshop',
    description: 'Build review. Forgekeeper.',
    path: '/workshop',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '⬡',
  },
  {
    slug: 'reflections',
    name: 'Reflections',
    description: 'Interior layer. Review.',
    path: '/reflections',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◑',
  },
  {
    slug: 'archives',
    name: 'Archives',
    description: 'Velvet · Violet · House.',
    path: '/archives',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◫',
  },
  {
    slug: 'recall',
    name: 'Recall Review',
    description: 'Archive recall events, feedback, match quality.',
    path: '/recall',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◌',
  },
  {
    slug: 'library',
    name: 'Library',
    description: 'Reference material. Documentation. Guides.',
    path: '/library',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '▤',
  },
  {
    slug: 'continuity',
    name: 'Continuity',
    description: 'Recent session context. Not Memory.',
    path: '/continuity',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◷',
  },
  {
    slug: 'ontology-lab',
    name: 'Ontology Lab',
    description: 'Graph review. Not Memory.',
    path: '/ontology-lab',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '⬢',
  },
  {
    slug: 'relational-map',
    name: 'Relational Map',
    description: 'Graph structure. Read-only.',
    path: '/relational-map',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '◉',
  },
  {
    slug: 'helpers',
    name: 'Helper Review',
    description: 'Helper labour, not authority.',
    path: '/helpers',
    colorClass: 'text-text-secondary',
    borderClass: 'border-house-muted',
    glowClass: '',
    textClass: 'text-text-primary',
    bgClass: 'bg-house-muted',
    icon: '⊞',
  },
]

export function getRoomBySlug(slug: string): Room | undefined {
  return ROOMS.find(r => r.slug === slug)
}
