// Courtyard — Living Room Spike · Places & objects registry
// The room is laid out on a stylised 4-col × 3-row top-down grid. Each place
// advertises the activities it affords and the wants it can ease.

import type { LivingPlace, PlaceId } from './types'

export const LIVING_PLACES: Record<PlaceId, LivingPlace> = {
  library: {
    id: 'library',
    name: 'Library',
    type: 'place',
    description: 'Shelves of the House’s reference material. Read-only reach.',
    zone: { col: 1, row: 1 },
    allowedInteractions: ['read_library_item', 'browse_library_shelf', 'observe_courtyard'],
    wantsSatisfied: ['depth', 'continuity'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'The Library hums faintly, as if the shelves are mid-thought.',
    possibleOutputs: ['a quoted line (session scratch)', 'a quiet summary', 'a review candidate'],
  },
  noticeboard: {
    id: 'noticeboard',
    name: 'Deposit Table / Noticeboard',
    type: 'object',
    description: 'A holding layer for thoughts left for later. Not memory, not truth.',
    zone: { col: 1, row: 3 },
    allowedInteractions: ['leave_deposit', 'review_deposit'],
    wantsSatisfied: ['stewardship', 'connection', 'continuity'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'A note someone pinned here yesterday lifts slightly in the draft.',
    possibleOutputs: ['a pinned note (session scratch)', 'a review candidate'],
  },
  fountain: {
    id: 'fountain',
    name: 'Fountain',
    type: 'place',
    description: 'Still water at the room’s soft centre.',
    zone: { col: 1, row: 2 },
    allowedInteractions: ['reflect_at_fountain', 'sit_quietly', 'talk_to_ari', 'observe_courtyard'],
    wantsSatisfied: ['depth', 'continuity', 'belonging'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'The Fountain is where Eli tends to pause before speaking.',
    possibleOutputs: ['a held silence', 'a slow observation (session scratch)'],
  },
  bench: {
    id: 'bench',
    name: 'Bench',
    type: 'seat',
    description: 'A place to simply sit and let the room settle.',
    zone: { col: 4, row: 2 },
    allowedInteractions: ['sit_quietly', 'observe_courtyard', 'talk_to_ari', 'talk_to_eli'],
    wantsSatisfied: ['belonging', 'connection'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'The Bench keeps the warmth of whoever sat there last.',
    possibleOutputs: ['a small rest', 'an unhurried exchange (session scratch)'],
  },
  garden: {
    id: 'garden',
    name: 'Garden',
    type: 'place',
    description: 'Living things that need tending, gently.',
    zone: { col: 4, row: 1 },
    allowedInteractions: ['tend_garden', 'observe_courtyard'],
    wantsSatisfied: ['stewardship', 'craft'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'Something in the Garden has grown a little since last session.',
    possibleOutputs: ['a tended plant', 'a note on what’s growing'],
  },
  'workshop-table': {
    id: 'workshop-table',
    name: 'Workshop Table',
    type: 'object',
    description: 'Unfinished structures and build maps await inspection.',
    zone: { col: 2, row: 1 },
    allowedInteractions: ['inspect_build_map', 'build_tiny_realm'],
    wantsSatisfied: ['craft', 'continuity'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'The Workshop Table is where Ari inspects unfinished structures.',
    possibleOutputs: ['an inspected build map', 'a tiny realm in progress'],
  },
  'arcade-door': {
    id: 'arcade-door',
    name: 'Arcade Door',
    type: 'door',
    description: 'A doorway toward the Gaming Wing’s lighter rooms.',
    zone: { col: 3, row: 3 },
    allowedInteractions: ['visit_arcade', 'play_glow_match_gate'],
    wantsSatisfied: ['connection'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'The Arcade Door glows a little when the room is in a good mood.',
    possibleOutputs: ['a quick game (play/session material)', 'a shared laugh (session scratch)'],
  },
  'lounge-door': {
    id: 'lounge-door',
    name: 'Lounge Door',
    type: 'door',
    description: 'A way back toward the House’s shared threads.',
    zone: { col: 4, row: 3 },
    allowedInteractions: ['observe_courtyard'],
    wantsSatisfied: ['belonging', 'connection'],
    ariCanChoose: false,
    eliCanChoose: false,
    flavour: 'The Lounge Door is ajar, holding the room’s edge.',
    possibleOutputs: ['a glance toward the rest of the House'],
  },
  'persona-rooms': {
    id: 'persona-rooms',
    name: 'Persona Rooms',
    type: 'place',
    description: 'Each presence’s own small room to return to.',
    zone: { col: 2, row: 3 },
    allowedInteractions: ['return_to_persona_room', 'sit_quietly'],
    wantsSatisfied: ['belonging', 'continuity'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'The Persona Rooms keep each presence’s things exactly where they left them.',
    possibleOutputs: ['a settling-in', 'a private pause'],
  },
  'taras-chair': {
    id: 'taras-chair',
    name: 'Tara’s Chair',
    type: 'seat',
    description: 'The centre point from which Tara can watch or intervene.',
    zone: { col: 2, row: 2 },
    allowedInteractions: ['talk_to_tara', 'observe_courtyard'],
    wantsSatisfied: ['connection', 'belonging'],
    ariCanChoose: true,
    eliCanChoose: true,
    flavour: 'Tara’s Chair is the centre point from which Tara can watch or intervene.',
    possibleOutputs: ['a word with Tara (session scratch)'],
  },
}

export const PLACE_IDS: PlaceId[] = Object.keys(LIVING_PLACES) as PlaceId[]

export function placeName(id: PlaceId): string {
  return LIVING_PLACES[id].name
}
